# Generated by Django 2.0.6 on 2018-06-24 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmarks',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField(blank=True, null=True)),
                ('imagepath', models.CharField(blank=True, db_column='imagePath', max_length=255, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='RecipesTags',
            fields=[
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tagsRecipe', serialize=False, to='recipes.Recipes')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipesTag', to='recipes.Tags')),
            ],
            options={
                'db_table': 'recipes_tags',
            },
        ),
        migrations.CreateModel(
            name='RecipesUsers',
            fields=[
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='usersRecipe', serialize=False, to='recipes.Recipes')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipesUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipes_users',
            },
        ),
        migrations.AddField(
            model_name='recipes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='recipesusers',
            unique_together={('recipes', 'users')},
        ),
        migrations.AlterUniqueTogether(
            name='recipestags',
            unique_together={('recipe', 'tag')},
        ),
    ]
